locals {
  rg_name                    = "rg-backend-meetup"
  location                   = "West Europe"
  sb1_name                   = "sb1-backend-meetup"
  topic1_name                = "topic1-backend-meetup"
  topic_eventgrid_name       = "topic-eventgrid-backend-meetup"
  eh_ns_name                 = "eh-ns-backend-meetup"
  eh1_name                   = "eh-backend-meetup-first"
  eh2_eventgrid_name         = "eh-eventgrid-backend-meetup"
  eg_topic_name              = "eg-topic-backend-meetup"
  sub1_name                  = "sub1-backend-meetup"
  sub3_name                  = "sub3-eventgrid-topic-backend-meetup"
  sub4_name                  = "sub4-eventgrid-eventhub-backend-meetup"
  meetup_queue_name          = "meetup"
  enqueue_time_consumer_name = "enqueue-time-consumer"
}
